---
- name: Setup DB Server
  hosts: dbserver
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    db_name: "wordpress_db"
    db_user: "wordpress_user"
    db_user_password: "wordpress_P@ssw0rd"
  tasks:
    - name: Ensure default gateway is set to 192.168.56.11
      command: ip route
      register: gateway_check
      ignore_errors: true
      
    - name: Set default gateway to 192.168.56.11 if not already set
      command: ip route add default via 192.168.56.11
      when: gateway_check.stdout.find("default via 192.168.56.11") == -1

    - name: Install MariaDB Server
      yum:
        name: mariadb-server
        state: present
​
    - name: Start MariaDB Service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Check if database exists
      shell: "mysql -u root -e 'SHOW DATABASES LIKE \"{{ db_name }}\";'"
      register: db_exists
      ignore_errors: true

    - name: Create Database
      shell: "mysql -u root -e 'CREATE DATABASE {{ db_name }};'"
      when: db_exists.stdout.find(db_name) == -1
      become: true
      become_user: root

    - name: Create DB User and Grant Privileges
      shell: >
        mysql -u root -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO '{{ db_user }}'@'192.168.56.*' IDENTIFIED BY '{{ db_user_password }}'; FLUSH PRIVILEGES;"
      become: true
      become_user: root
