---
- name: Setup LB-01 server
  hosts: lbserver
  tasks:
    - name: Ensure default gateway is set to 10.0.2.2
      command: ip route
      register: gateway_check
      ignore_errors: true

    - name: Set default gateway to 10.0.2.2 if not already set
      command: ip route add default via 10.0.2.2
      when: gateway_check.stdout.find("default via 10.0.2.2") == -1

    - name: Ensure IP forwarding is enabled in sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 1'
        state: present

    # - name: Apply sysctl settings
    #   command: sysctl -p
    #   become: true

    - name: Install HAProxy
      yum:
        name: haproxy
        state: present

    - name: Start HAProxy service
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: Install caching-nameserver
      yum:
        name: bind
        state: present
    
    - name: start named serive
      service:
        name: named
        state: started
        enabled: yes
    
    - name: set Haproxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
    
    - name: set DNS
      template:
        src: "{{ item }}"
        dest: /etc
      loop:
        - templates/named.conf.j2
        - templates/named.rfc1912.zones.j2

    - name: set DNS Zonefile
      template:
        src: "{{ item }}.j2"
        dest: /var/named/{{ item }}
      loop:
        - templates/web01.example.com.zone
        - templates/web02.example.com.zone
        - templates/wordpress.example.com.zone
