---
- name: Setup Web-02 Server
  hosts: Web-02
  become: true
  tasks:
    - name: Ensure default gateway is set to 10.0.2.2
      command: ip route
      register: gateway_check
      ignore_errors: true

    - name: Set default gateway to 10.0.2.2
      command: ip route add default via 10.0.2.2 dev enp0s3 proto static metric 100
      when: gateway_check.stdout.find("default via 10.0.2.2") == -1

    - name: Install Apache Web Server
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create NFS directory for Web-02
      file:
        path: /srv/web/web02
        state: directory
